### ISSUE TITLE
a gravity ring part bug

### ISSUE THREAD

**Issue by sagara9892** [jsud0/InterplanetaryTech#2]
the gravity ring cant do anything if i install Dynamic Engine Effects mod

**Comment by jsud0** [comment]
Updating the Dynamic Engine Effects should fix the bug. The older one conflicts with this mod due to my silly mistake.

**Comment by sagara9892** [comment]
should i wait for an update for the Dynamic Engine Effects mod or do what. also thank you for responding

**Comment by ForeverFlank** [comment]
I already updated them a while ago. Also to be sure, update the balloon mod to the latest version too.

**Comment by jsud0** [comment]
I already updated them a while ago. Also to be sure, update the balloon mod to the latest version too.

**Comment by sagara9892** [comment]
i tried it but it still doesnt work https://drive.google.com/file/d/1itzzeqfrQYYs8dxcK_2Y5SOe5ddz1JdB/view?usp=sharing can you pls help

**Comment by jsud0** [comment]
Can you check and show me the debug log (by pressing F1) and see if there are errors like NullPointerException?

**Comment by sagara9892** [comment]
https://imgur.com/a/RHhzUuU ok

**Comment by jsud0** [comment]
Yup, something is clearly wrong. Can I have the screenshot of the main screen mod menu? Maybe I can check if another mod is doing weird things to it.

**Comment by sagara9892** [comment]
wait now i will try to trobleshoot https://imgur.com/a/RHhzUuU same link there is new image

**Comment by sagara9892** [comment]
mod list https://imgur.com/a/jahxfWI

**Comment by jsud0** [comment]
Can you try this instead? [Mods.zip](https://github.com/user-attachments/files/21661297/Mods.zip)

**Comment by sagara9892** [comment]
ok here is the link https://drive.google.com/file/d/1E2avydOKeEwLxlRCNiV8DQj02UcjnhQN/view?usp=sharing

**Comment by sagara9892** [comment]
i remove the ui mods https://imgur.com/a/1NDJtvb and it still dosent work

**Comment by sagara9892** [comment]
i also used the newest versions of the mods

**Comment by sagara9892** [comment]
> Can you try this instead? [Mods.zip](https://github.com/user-attachments/files/21661297/Mods.zip)

sorry i didnt read it right good news it works. thank you also can you update the download link page

**Comment by jsud0** [comment]
Updated the mod file.
